// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_db.Models;

#nullable disable

namespace dotnet_db.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260121140607_AddSliders")]
    partial class AddSliders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("dotnet_db.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Kozmetik",
                            Url = "kozmetik"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Kategori-1",
                            Url = "kategori-1"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Kategori-2",
                            Url = "kategori-2"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Kategori-3",
                            Url = "kategori-3"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Kategori-4",
                            Url = "kategori-4"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Kategori-5",
                            Url = "kategori-5"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Kategori-6",
                            Url = "kategori-6"
                        });
                });

            modelBuilder.Entity("dotnet_db.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Img")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae ullam dicta sapiente recusandae? Accusamus, suscipit consequuntur doloribus magnam corrupti sed obcaecati quas vel ipsam eos exercitationem modi deserunt alias voluptas?",
                            Img = "1.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Name = "Iphone 13",
                            Price = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae ullam dicta sapiente recusandae? Accusamus, suscipit consequuntur doloribus magnam corrupti sed obcaecati quas vel ipsam eos exercitationem modi deserunt alias voluptas?",
                            Img = "2.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Name = "Iphone 14",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae ullam dicta sapiente recusandae? Accusamus, suscipit consequuntur doloribus magnam corrupti sed obcaecati quas vel ipsam eos exercitationem modi deserunt alias voluptas?",
                            Img = "3.jpeg",
                            IsActive = false,
                            IsHome = true,
                            Name = "Iphone 15",
                            Price = 30000.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae ullam dicta sapiente recusandae? Accusamus, suscipit consequuntur doloribus magnam corrupti sed obcaecati quas vel ipsam eos exercitationem modi deserunt alias voluptas?",
                            Img = "4.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Name = "Iphone 16",
                            Price = 40000.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae ullam dicta sapiente recusandae? Accusamus, suscipit consequuntur doloribus magnam corrupti sed obcaecati quas vel ipsam eos exercitationem modi deserunt alias voluptas?",
                            Img = "5.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Name = "Iphone 17",
                            Price = 50000.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae ullam dicta sapiente recusandae? Accusamus, suscipit consequuntur doloribus magnam corrupti sed obcaecati quas vel ipsam eos exercitationem modi deserunt alias voluptas?",
                            Img = "6.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Name = "Iphone 17",
                            Price = 60000.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae ullam dicta sapiente recusandae? Accusamus, suscipit consequuntur doloribus magnam corrupti sed obcaecati quas vel ipsam eos exercitationem modi deserunt alias voluptas?",
                            Img = "7.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Name = "Iphone 17",
                            Price = 70000.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae ullam dicta sapiente recusandae? Accusamus, suscipit consequuntur doloribus magnam corrupti sed obcaecati quas vel ipsam eos exercitationem modi deserunt alias voluptas?",
                            Img = "8.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Name = "Iphone 17",
                            Price = 80000.0
                        });
                });

            modelBuilder.Entity("dotnet_db.Models.Product", b =>
                {
                    b.HasOne("dotnet_db.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("dotnet_db.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
