// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_db.Models;

#nullable disable

namespace dotnet_db.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260120152624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("dotnet_db.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Name = "Iphone 13",
                            Price = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Iphone 14",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "Iphone 15",
                            Price = 30000.0
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Iphone 16",
                            Price = 40000.0
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Iphone 17",
                            Price = 50000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
